//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCTool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MFCToolTYPE                 130
#define IDD_DIALOG1                     310
#define IDD_MYFORMVIEW                  310
#define IDD_TAP01                       312
#define IDD_TAP02                       314
#define IDD_TAP03                       315
#define IDD_Tap04                       318
#define IDD_DIALOG2                     320
#define IDC_TAB1                        1000
#define IDC_BUTTON1                     1001
#define IDC_RADIO1                      1002
#define IDC_BUTTON_LOAD_TEXTURE         1003
#define IDC_RADIO_LESS                  1003
#define IDC_BT_SET                      1004
#define IDC_RADIO5                      1004
#define IDC_RADIO_MANY                  1004
#define IDC_RADIO2                      1005
#define IDC_RADIO3                      1006
#define IDC_SLIDER_ALPHA                1007
#define IDC_BT_DELETE                   1008
#define IDC_CHECK_INTERVAL              1009
#define IDC_EDIT_BLUE                   1010
#define IDC_CHECK1                      1011
#define IDC_EDIT_RED                    1012
#define IDC_EDIT_ALPHA                  1013
#define IDC_EDIT4                       1014
#define IDC_EDIT_GREEN                  1015
#define IDC_hanCHECK_SET_CHECKER        1016
#define IDC_SPIN2                       1017
#define IDC_SPIN_BoxZ                   1018
#define IDC_EDIT6                       1019
#define IDC_SPIN_BoxX                   1020
#define IDC_SPIN3                       1021
#define IDC_SPIN4                       1022
#define IDC_EDIT7                       1023
#define IDC_BUTTON2                     1024
#define IDC_BUTTON_SET                  1025
#define IDC_ED_m11                      1026
#define IDC_ED_m12                      1027
#define IDC_ED_m13                      1028
#define IDC_ED_m21                      1029
#define IDC_ED_m22                      1030
#define IDC_ED_m23                      1031
#define IDC_ED_m31                      1032
#define IDC_ED_m32                      1033
#define IDC_ED_m33                      1034
#define IDC_ED_m41                      1035
#define IDC_ED_m42                      1036
#define IDC_ED_m43                      1037
#define IDC_SLIDER_RED                  1038
#define IDC_SLIDER_RED__                1038
#define IDC_SLIDER_BLUE                 1040
#define IDC_SLIDER_BLUE__               1040
#define IDC_BTN_Play                    1041
#define IDC_BTN_Stop                    1042
#define IDC_LIST_OBJECTPLATE            1043
#define IDC_ED_OBJECTNAME               1044
#define IDC_EDe_                        1045
#define IDC_EDe_16                      1046
#define IDC_BTN_LOAD                    1047
#define IDC_BTN_APPLY                   1048
#define IDC_ED_REDVALUE                 1049
#define IDC_ED_GREENVALUE               1050
#define IDC_ED_BLUEVALUE                1051
#define IDC_BTN_SAVE                    1052
#define IDC_EDe_17                      1053
#define IDC_EDe_18                      1054
#define IDC_CHECK3                      1055
#define IDC_ED_RADIUSMIN                1056
#define IDC_ED_RADIUSMAX                1057
#define IDC_CHECK4                      1058
#define IDC_CHECK5                      1059
#define IDC_ED_LIFETIMEMIN              1060
#define IDC_CHECK_COLORBEGIN            1061
#define IDC_CHECK_COLOREND              1062
#define IDC_ED_LIFETIMEMAX              1063
#define IDC_ED_LIFETIMEDELAY            1064
#define IDC_EDe_19                      1065
#define IDC_EDe_20                      1066
#define IDC_BTN_OBJECT_ADD              1067
#define IDC_BTN_OBJECT_DELETE           1068
#define IDC_CHEK_APPLY_GRAVITY          1069
#define IDC_ED_GRAVITYMIN               1070
#define IDC_ED_GRAVITYMAX               1071
#define IDC_ED_OBJECTNUM                1072
#define IDC_BTN_CLEAR                   1073
#define IDC_ED_MinX                     1074
#define IDC_ED_MinY                     1075
#define IDC_ED_MinZ                     1076
#define IDC_ED_MaxX                     1077
#define IDC_ED_MaxY                     1078
#define IDC_EDe_25                      1079
#define IDC_ED_MaxZ                     1079
#define IDC_BUTTON_REMOVE2              1080
#define IDC_LIST_CUBE                   1081
#define IDC_CHECK_MULTY                 1081
#define IDC_BUTTON_INSTALL              1082
#define IDC_RADIO_SINGLE                1082
#define IDC_BUTTON_MONSTERLOAD          1083
#define IDC_BUTTON_SAVEALL              1084
#define IDC_STATIC_CUBEGROUP            1086
#define IDC_COMBOBOXEX1                 1086
#define IDC_COMBOBOXEX_TYPE             1086
#define IDC_StaticLoad                  1086
#define IDC_STATIC_MONSTERGROUP         1087
#define IDC_RADIO_CONST                 1087
#define IDC_Erase_Han                   1087
#define IDC_EDIT_OBJECTPOINT            1088
#define IDC_RADIO_RANDOM                1088
#define IDC_LIST_MONSTER                1089
#define IDC_STATIC_ETCGROUP             1090
#define IDC_RADIO_TYPE1                 1090
#define IDC_LIST_ETC                    1091
#define IDC_RADIO_TYPE2                 1091
#define IDC_BUTTON_ETCLOAD              1092
#define IDC_RADIO_TYPE3                 1092
#define IDC_BUTTON_CUBELOAD             1093
#define IDC_SLIDER_ALPHA_               1107
#define IDC_SPIN_BoxY                   1121
#define IDC_EDIT_BoxXYZ                 1123
#define IDC_BUTTON_LOAD                 1124
#define IDC_BUTTON_SAVE                 1125
#define IDC_LIST_TEXTUREFILE            1126
#define IDC_BUTTON3                     1127
#define IDC_EDIT2                       1128
#define IDC_PICTURE                     1129
#define IDC_EDPOSX                      1130
#define IDC_EDPOSY                      1131
#define IDC_EDPOSZ                      1132
#define IDC_EDVX                        1133
#define IDC_EDVY                        1134
#define IDC_EDVZ                        1135
#define IDC_BT_LOAD                     1136
#define IDC_EDINTERVALVALUE             1137
#define IDC_EDCOUNT                     1138
#define IDC_SLIDER_GREEN                1139
#define IDC_SLIDER_GREEN__              1139
#define IDC_EDSCALEY                    1140
#define IDC_EDSCALEZ                    1141
#define IDC_LIST_OBJECT                 1142
#define IDC_CHECK_CHAIN                 1144
#define IDC_CHECK_SNAP                  1145
#define IDC_BT_INVERSE                  1146
#define IDC_EDNAME                      1148
#define IDC_CHECK_AllSAVE               1150
#define IDC_BT_Fix                      1151
#define IDC_hanCHECK_CubeColor          1152
#define IDC_hanCHECK_CubeTexture        1153
#define IDC_hanCHECK_SliderColor        1154
#define IDC_hanCHECK_SliderTexture      1155
#define IDC_hanCHECK_Etc                1157
#define IDC_hanCHECK_Red                1158
#define IDC_hanCHECK_Green              1159
#define IDC_hanCHECK_Blue               1160
#define IDC_BT_ROTX                     1224
#define IDC_BT_ROTY                     1225
#define IDC_BT_ROTZ                     1226
#define IDC_BUTTON_REMOVE               1227
#define IDC_hanBT_UpZSet                1227
#define IDC_EDIT_WRITENAME              1228
#define IDC_hanBT_DownXSet              1228
#define IDC_hanBT_UpXSet                1229
#define IDC_hanBT_DownZSet              1230
#define IDC_hanBT_UpYSet                1231
#define IDC_hanBT_DownYSet              1232
#define IDC_SLIDER_RED_                 1238
#define IDC_EDSCALEX                    1239
#define IDC_SLIDER_BLUE_                1240
#define IDC_LIST_TEXTURE                1243
#define IDC_BT_CLEAR                    1327
#define IDC_BT_SAVE                     1328
#define IDC_SLIDER_GREEN_               1339

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
