#ifndef define_h__
#define define_h__

#define WINCX 800
#define WINCY 600


#define OBJ_DEAD 1
#define OBJ_NOEVENT 0

extern HWND			g_hWnd;
extern HINSTANCE	g_hInst;
extern bool			exColisionSee;
extern bool			exMapSee;

enum UIID { UIID_FRAME, UIID_HPBAR, UIID_STEMINABAR, UIID_ITEMBACK, UIID_HP_POTION, UIID_SP_POTION, UIID_ITEM_HPEND, UIID_VICTORY, UIID_END };


enum EFFECTID {EFFECT_AURA,EFFECT_RING,EFFECT_END};

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_STAGE, RESOURCE_END };
enum LAYERID	{ LAYER_ENVIRONMENT, LAYER_GAMELOGIC, LAYER_UI, LAYER_END };
enum LOADINGID	{ LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum SPHEREID	{	SPHERE_HEAD, 
					SPHERE_NK00, SPHERE_NK01, SPHERE_NK02,
					SPHERE_WR00, SPHERE_WR01, SPHERE_WR02,
					SPHERE_WL00, SPHERE_WL01, SPHERE_WL02,
					SPHERE_LL00, SPHERE_LL01, SPHERE_LL02, SPHERE_LL03,
					SPHERE_LR00, SPHERE_LR01, SPHERE_LR02, SPHERE_LR03,
					SPHERE_AR00, SPHERE_AR01, SPHERE_AR02, SPHERE_AR03,
					SPHERE_AL00, SPHERE_AL01, SPHERE_AL02, SPHERE_AL03,
					SPHERE_FL00,
					SPHERE_FR00,
					SPHERE_TL00, SPHERE_TL01, SPHERE_TL02, SPHERE_TL03, SPHERE_TL04, SPHERE_TL05,
					SPHERE_END };

enum WP_SPHEREID {WP_00, /*WP_01, WP_02, WP_03, WP_04,*/ WP_END};

enum PLAYER_SPHEREID {PLAYER_00 , PLAYER_END};


enum NAVIID{NAVI_NORMAL, NAVI_DOWN ,NAVI_END};




#endif // define_h__
