#pragma once
#ifndef __CODYSPACEANIMENUM_H__

enum Cody_Space_AnimID {
	Cody_Space_Idle,                                     //0	frame:[84]
	Cody_Space_Walk,                                     //1	frame:[34]
	Cody_Space_Run,                                      //2	frame:[24]
	Cody_Space_Jump,                                     //3	frame:[45]
	Cody_Space_2ndJump,                                  //4	frame:[47]
	Cody_Space_Jump_Fall,                                //5	frame:[25]
	Cody_Space_Jump_Land,                                //6	frame:[14]
	Cody_Space_Crouch_Start,                             //7	frame:[11]
	Cody_Space_Crouch_Idle,                              //8	frame:[61]
	Cody_Space_Crouch_End,                               //9	frame:[11]
	Cody_Space_Crouch_Walk_Start,                        //10	frame:[10]
	Cody_Space_Crouch_Walk,                              //11	frame:[13]
	Cody_Space_Crouch_Walk_End,                          //12	frame:[16]
	Cody_Space_Wall_Idle,                                //13	frame:[30]
	Cody_Space_Wall_Jump,                                //14	frame:[19]
	Cody_Space_Fall,                                     //15	frame:[41]
	Cody_Space_Push,                                     //16	frame:[25]
	Cody_Space_Push_Idle,                                //17	frame:[31]
	Cody_Space_Pull,                                     //18	frame:[24]
	Cody_Space_Push_Button,                              //19	frame:[36]
	Cody_Space_Jump_Dash,                                //20	frame:[30]
	Cody_Space_Dash_Start,                               //21	frame:[14]
	Cody_Space_Dash_End,                                 //22	frame:[18]
	Cody_Space_Ledge_Start,                              //23	frame:[14]
	Cody_Space_Ledge_Idle,                               //24	frame:[91]
	Cody_Space_Ledge_Drop,                               //25	frame:[8]
	Cody_Space_Ledge_ClimbUp,                            //26	frame:[25]
	Cody_Space_Ledge_ClimbLeft,                          //27	frame:[15]
	Cody_Space_Ledge_ClimbRight,                         //28	frame:[15]
	Cody_Space_LeverRightToLeft,                         //29	frame:[36]
	Cody_Space_LeverLeftToRight,                         //30	frame:[31]
	Cody_Space_GroundPound_Start,                        //31	frame:[16]
	Cody_Space_GroundPound_Fall,                         //32	frame:[31]
	Cody_Space_GroundPound_Land,                         //33	frame:[12]
	Cody_Space_GroundPound_End,                          //34	frame:[16]
	Cody_Space_Hose_Start,                               //35	frame:[19]
	Cody_Space_Hose_Idle,                                //36	frame:[29]
	Cody_Space_Hose_Up,                                  //37	frame:[29]
	Cody_Space_Hose_Left,                                //38	frame:[29]
	Cody_Space_Hose_Right,                               //39	frame:[29]
	Cody_Space_Hose_End,                                 //40	frame:[21]
	Cody_Space_Zerogravity_Idle,                         //41	frame:[31]
	Cody_Space_LeverLeft,                                //42	frame:[23]
	Cody_Space_LeverRight,                               //43	frame:[23]
	Cody_Space_Wall_VerticalJump,                        //44	frame:[23]
	Cody_Space_Valve_Idle,                               //45	frame:[66]
	Cody_Space_Valve_RotateRight,                        //46	frame:[61]
	Cody_Space_JumpDash_End,                             //47	frame:[19]
	Cody_Space_SizeUp_Walk,                              //48	frame:[24]
	Cody_Space_SizeUp_GroundPound_Start,                 //49	frame:[16]
	Cody_Space_SizeUp_GroundPound_Fall,                  //50	frame:[31]
	Cody_Space_SizeUp_GroundPound_Land,                  //51	frame:[61]
	Cody_Space_SizeUp_GroundPound_End,                   //52	frame:[30]
	Cody_Space_Hit,                                      //53	frame:[20]
	Cody_Space_End

};

#define __CODYSPACEANIMENUM_H__
#endif