#pragma once
#ifndef __CODYANIMENUM_H__

enum Cody_AnimID {
	Cody_Idle,                                     //0	frame:[84]
	Cody_Walk,                                     //1	frame:[34]
	Cody_Run,                                      //2	frame:[24]
	Cody_Jump,                                     //3	frame:[45]
	Cody_2ndJump,                                  //4	frame:[47]
	Cody_Jump_Fall,                                //5	frame:[25]
	Cody_Jump_Land,                                //6	frame:[14]
	Cody_Crouch_Start,                             //7	frame:[11]
	Cody_Crouch_Idle,                              //8	frame:[61]
	Cody_Crouch_End,                               //9	frame:[11]
	Cody_Crouch_Walk_Start,                        //10	frame:[10]
	Cody_Crouch_Walk,                              //11	frame:[13]
	Cody_Crouch_Walk_End,                          //12	frame:[16]
	Cody_Wall_Idle,                                //13	frame:[30]
	Cody_Wall_Jump,                                //14	frame:[19]
	Cody_Slide_Start,                              //15	frame:[22]
	Cody_Slide,                                    //16	frame:[61]
	Cody_Slide_End,                                //17	frame:[15]
	Cody_Slide_Left,                               //18	frame:[61]
	Cody_Slide_Right,                              //19	frame:[61]
	Cody_Fall,                                     //20	frame:[41]
	Cody_Fall_Oil,                                 //21	frame:[36]
	Cody_Push,                                     //22	frame:[25]
	Cody_Push_Idle,                                //23	frame:[31]
	Cody_Pull,                                     //24	frame:[24]
	Cody_Push_Button,                              //25	frame:[36]
	Cody_Jump_Dash,                                //26	frame:[30]
	Cody_Dash_Start,                               //27	frame:[14]
	Cody_Dash_End,                                 //28	frame:[18]
	Cody_Ledge_Start,                              //29	frame:[14]
	Cody_Ledge_Idle,                               //30	frame:[91]
	Cody_Ledge_Drop,                               //31	frame:[8]
	Cody_Ledge_ClimbUp,                            //32	frame:[25]
	Cody_Ledge_ClimbLeft,                          //33	frame:[15]
	Cody_Ledge_ClimbRight,                         //34	frame:[15]
	Cody_LeverRightToLeft,                         //35	frame:[36]
	Cody_LeverLeftToRight,                         //36	frame:[31]
	Cody_GroundPound_Start,                        //37	frame:[16]
	Cody_GroundPound_Fall,                         //38	frame:[31]
	Cody_GroundPound_Land,                         //39	frame:[12]
	Cody_GroundPound_End,                          //40	frame:[16]
	Cody_Pickup,                                   //41	frame:[25]
	Cody_Pickup_Idle,                              //42	frame:[84]
	Cody_Pickup_Walk,                              //43	frame:[34]
	Cody_Pickup_Jump_Start,                        //44	frame:[45]
	Cody_Pickup_Jump_Fall,                         //45	frame:[25]
	Cody_Pickup_Jump_Land,                         //46	frame:[14]
	Cody_Pickup_PutDown,                           //47	frame:[21]
	Cody_Pickup_FusePutinSocket,                   //48	frame:[26]
	Cody_Hose_Start,                               //49	frame:[19]
	Cody_Hose_Idle,                                //50	frame:[29]
	Cody_Hose_Up,                                  //51	frame:[29]
	Cody_Hose_Left,                                //52	frame:[29]
	Cody_Hose_Right,                               //53	frame:[29]
	Cody_Hose_End,                                 //54	frame:[21]
	Cody_Hose_SuckedIn,                            //55	frame:[14]
	Cody_Hose_Inside,                              //56	frame:[9]
	Cody_Hose_BlowOut,                             //57	frame:[29]
	Cody_PowerSwitch_Start,                        //58	frame:[11]
	Cody_PowerSwitch_Idle,                         //59	frame:[41]
	Cody_PowerSwitch_Success,                      //60	frame:[26]
	Cody_VacuumLaunch_Start,                       //61	frame:[45]
	Cody_VacuumLaunch_Idle,                        //62	frame:[31]
	Cody_VacuumLaunch_IdleEnd,                     //63	frame:[41]
	Cody_Zerogravity_Idle,                         //64	frame:[31]
	Cody_LeverLeft,                                //65	frame:[23]
	Cody_LeverRight,                               //66	frame:[23]
	Cody_Wall_VerticalJump,                        //67	frame:[23]
	Cody_Valve_Idle,                               //68	frame:[66]
	Cody_Valve_RotateRight,                        //69	frame:[61]
	Cody_JumpDash_End,                             //70	frame:[19]
	Cody_Grind_Start,                              //71	frame:[20]
	Cody_Grind_Idle,                               //72	frame:[65]
	Cody_Grind_End,                                //73	frame:[17]
	Cody_SizeUp_Walk,                              //74	frame:[24]
	Cody_SizeUp_GroundPound_Start,                 //75	frame:[16]
	Cody_SizeUp_GroundPound_Fall,                  //76	frame:[31]
	Cody_SizeUp_GroundPound_Land,                  //77	frame:[61]
	Cody_SizeUp_GroundPound_End,                   //78	frame:[30]
	Cody_Hit,
};

#define __CODYANIMENUM_H__
#endif