#pragma once
#ifndef __MAYSPACEANIMENUM_H__

namespace SPACE {
	enum May_Space_AnimID {
		May_Idle,                                     //0	frame:[61]
		May_Walk,                                     //1	frame:[21]
		May_Run,                                      //2	frame:[13]
		May_Jump,                                     //3	frame:[48]
		May_2ndJump,                                  //4	frame:[57]
		May_Jump_Fall,                                //5	frame:[19]
		May_Jump_Land,                                //6	frame:[14]
		May_Crouch_Start,                             //7	frame:[11]
		May_Crouch_Idle,                              //8	frame:[25]
		May_Crouch_End,                               //9	frame:[11]
		May_Crouch_Walk_Start,                        //10	frame:[15]
		May_Crouch_Walk,                              //11	frame:[29]
		May_Crouch_Walk_End,                          //12	frame:[9]
		May_Wall_Idle,                                //13	frame:[31]
		May_Wall_Jump,                                //14	frame:[19]
		May_Fall,                                     //15	frame:[25]
		May_Push,                                     //16	frame:[31]
		May_Push_Idle,                                //17	frame:[61]
		May_Pull,                                     //18	frame:[31]
		May_Push_Button,                              //19	frame:[36]
		May_Jump_Dash,                                //20	frame:[31]
		May_Dash_Start,                               //21	frame:[14]
		May_Dash_End,                                 //22	frame:[19]
		May_Ledge_Start,                              //23	frame:[16]
		May_Ledge_Idle,                               //24	frame:[90]
		May_Ledge_ClimbUp,                            //25	frame:[25]
		May_Lever_RightToLeft,                        //26	frame:[36]
		May_Lever_LeftToRight,                        //27	frame:[31]
		May_GroundPound_Start,                        //28	frame:[16]
		May_GroundPound_Fall,                         //29	frame:[31]
		May_GroundPound_Land,                         //30	frame:[12]
		May_GroundPound_End,                          //31	frame:[19]
		May_Hose_Start,                               //32	frame:[17]
		May_Hose_Idle,                                //33	frame:[29]
		May_Hose_Up,                                  //34	frame:[29]
		May_Hose_Left,                                //35	frame:[29]
		May_Hose_Right,                               //36	frame:[29]
		May_Hose_End,                                 //37	frame:[21]
		May_PowerSwitch_Start,                        //38	frame:[11]
		May_PowerSwitch_Idle,                         //39	frame:[41]
		May_Zerogravity_Idle,                         //40	frame:[31]
		May_LeverLeft,                                //41	frame:[23]
		May_LeverRight,                               //42	frame:[23]
		May_Wall_VerticalJump,                        //43	frame:[31]
		May_Valve_Idle,                               //44	frame:[66]
		May_Valve_RotateRight,                        //45	frame:[61]
		May_JumpDash_End,                             //46	frame:[26]
		May_CubeMove_Start,                           //47	frame:[11]
		May_CubeMove_End,                             //48	frame:[13]
		May_CubeMove_Idle,                            //49	frame:[84]
		May_CubeMove_Fwd,                             //50	frame:[16]
		May_CubeMove_Fwd_Right,                       //51	frame:[16]
		May_CubeMove_Right,                           //52	frame:[16]
		May_CubeMove_Bwd_Right,                       //53	frame:[16]
		May_CubeMove_Bwd,                             //54	frame:[16]
		May_CubeMove_Bwd_Left,                        //55	frame:[16]
		May_CubeMove_Left,                            //56	frame:[16]
		May_CubeMove_Fwd_Left,                        //57	frame:[16]
		May_Hit,                                      //58	frame:[20]
		May_End

	};
}
#define __MAYSPACEANIMENUM_H__
#endif